/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoguinController;
import Model.DAO.Banco;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author João Pedro
 */
public class Loguin extends javax.swing.JFrame {

     private final LoguinController controller;
    /**
     * Creates new form Loguin
     */
    public Loguin() {
        initComponents();
        
        URL caminhoicon = getClass().getResource("/View/Imagens/Icons/Logojoao.png");
        Image iconetitulo = Toolkit.getDefaultToolkit().getImage(caminhoicon);
        this.setIconImage(iconetitulo);
        
        controller= new LoguinController(this);
        Banco.inicia();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entrar = new javax.swing.JButton();
        JTextSenha = new javax.swing.JPasswordField();
        jTextUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loguin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 160, 40));
        getContentPane().add(JTextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 310, 40));
        getContentPane().add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 310, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/loguin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
            this.controller.entrarnomenu();

    }//GEN-LAST:event_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loguin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JPasswordField JTextSenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables

    
    
    
    public JPasswordField getJTextSenha() {
        return JTextSenha;
    }

    public void setJTextSenha(JPasswordField JTextSenha) {
        this.JTextSenha = JTextSenha;
    }

    public JTextField getjTextUser() {
        return jTextUser;
    }

    public void setjTextUser(JTextField jTextUser) {
        this.jTextUser = jTextUser;
    }

    

}
